//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.296
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

// 
// 此源代码是由 Microsoft.VSDesigner 4.0.30319.296 版自动生成。
// 
#pragma warning disable 1591

namespace WindowsFormsApplication3.Getcoupon {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.ComponentModel;
    using System.Xml.Serialization;
    using System.Data;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="couponServiceSoap", Namespace="http://tempuri.org/")]
    public partial class couponService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback GetNewPCwithTidOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetAllPCwithTIDOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetNewPCwithPOSOperationCompleted;
        
        private System.Threading.SendOrPostCallback getCouponTypeOperationCompleted;
        
        private System.Threading.SendOrPostCallback ValidatePCOperationCompleted;
        
        private System.Threading.SendOrPostCallback ConsumePCOperationCompleted;
        
        private System.Threading.SendOrPostCallback csmSuccessOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetZF_SMS_DATAOperationCompleted;
        
        private System.Threading.SendOrPostCallback SetSMS_DATA_STATEOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetChangePointPCOperationCompleted;
        
        private System.Threading.SendOrPostCallback DelChangePointLogOperationCompleted;
        
        private System.Threading.SendOrPostCallback PosVipOpenPCOperationCompleted;
        
        private System.Threading.SendOrPostCallback SendSaleMsgOperationCompleted;
        
        private System.Threading.SendOrPostCallback SendLpcApplyResMsgOperationCompleted;
        
        private System.Threading.SendOrPostCallback helloOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public couponService() {
            this.Url = global::WindowsFormsApplication3.Properties.Settings.Default.DataProcessSystem_Getcoupon_couponService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event GetNewPCwithTidCompletedEventHandler GetNewPCwithTidCompleted;
        
        /// <remarks/>
        public event GetAllPCwithTIDCompletedEventHandler GetAllPCwithTIDCompleted;
        
        /// <remarks/>
        public event GetNewPCwithPOSCompletedEventHandler GetNewPCwithPOSCompleted;
        
        /// <remarks/>
        public event getCouponTypeCompletedEventHandler getCouponTypeCompleted;
        
        /// <remarks/>
        public event ValidatePCCompletedEventHandler ValidatePCCompleted;
        
        /// <remarks/>
        public event ConsumePCCompletedEventHandler ConsumePCCompleted;
        
        /// <remarks/>
        public event csmSuccessCompletedEventHandler csmSuccessCompleted;
        
        /// <remarks/>
        public event GetZF_SMS_DATACompletedEventHandler GetZF_SMS_DATACompleted;
        
        /// <remarks/>
        public event SetSMS_DATA_STATECompletedEventHandler SetSMS_DATA_STATECompleted;
        
        /// <remarks/>
        public event GetChangePointPCCompletedEventHandler GetChangePointPCCompleted;
        
        /// <remarks/>
        public event DelChangePointLogCompletedEventHandler DelChangePointLogCompleted;
        
        /// <remarks/>
        public event PosVipOpenPCCompletedEventHandler PosVipOpenPCCompleted;
        
        /// <remarks/>
        public event SendSaleMsgCompletedEventHandler SendSaleMsgCompleted;
        
        /// <remarks/>
        public event SendLpcApplyResMsgCompletedEventHandler SendLpcApplyResMsgCompleted;
        
        /// <remarks/>
        public event helloCompletedEventHandler helloCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetNewPCwithTid", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GetNewPCwithTid(string xmlStr) {
            object[] results = this.Invoke("GetNewPCwithTid", new object[] {
                        xmlStr});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetNewPCwithTidAsync(string xmlStr) {
            this.GetNewPCwithTidAsync(xmlStr, null);
        }
        
        /// <remarks/>
        public void GetNewPCwithTidAsync(string xmlStr, object userState) {
            if ((this.GetNewPCwithTidOperationCompleted == null)) {
                this.GetNewPCwithTidOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetNewPCwithTidOperationCompleted);
            }
            this.InvokeAsync("GetNewPCwithTid", new object[] {
                        xmlStr}, this.GetNewPCwithTidOperationCompleted, userState);
        }
        
        private void OnGetNewPCwithTidOperationCompleted(object arg) {
            if ((this.GetNewPCwithTidCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetNewPCwithTidCompleted(this, new GetNewPCwithTidCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetAllPCwithTID", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GetAllPCwithTID(string sql, string xmlStr) {
            object[] results = this.Invoke("GetAllPCwithTID", new object[] {
                        sql,
                        xmlStr});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetAllPCwithTIDAsync(string sql, string xmlStr) {
            this.GetAllPCwithTIDAsync(sql, xmlStr, null);
        }
        
        /// <remarks/>
        public void GetAllPCwithTIDAsync(string sql, string xmlStr, object userState) {
            if ((this.GetAllPCwithTIDOperationCompleted == null)) {
                this.GetAllPCwithTIDOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetAllPCwithTIDOperationCompleted);
            }
            this.InvokeAsync("GetAllPCwithTID", new object[] {
                        sql,
                        xmlStr}, this.GetAllPCwithTIDOperationCompleted, userState);
        }
        
        private void OnGetAllPCwithTIDOperationCompleted(object arg) {
            if ((this.GetAllPCwithTIDCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetAllPCwithTIDCompleted(this, new GetAllPCwithTIDCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetNewPCwithPOS", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GetNewPCwithPOS(string xmlStr) {
            object[] results = this.Invoke("GetNewPCwithPOS", new object[] {
                        xmlStr});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetNewPCwithPOSAsync(string xmlStr) {
            this.GetNewPCwithPOSAsync(xmlStr, null);
        }
        
        /// <remarks/>
        public void GetNewPCwithPOSAsync(string xmlStr, object userState) {
            if ((this.GetNewPCwithPOSOperationCompleted == null)) {
                this.GetNewPCwithPOSOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetNewPCwithPOSOperationCompleted);
            }
            this.InvokeAsync("GetNewPCwithPOS", new object[] {
                        xmlStr}, this.GetNewPCwithPOSOperationCompleted, userState);
        }
        
        private void OnGetNewPCwithPOSOperationCompleted(object arg) {
            if ((this.GetNewPCwithPOSCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetNewPCwithPOSCompleted(this, new GetNewPCwithPOSCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/getCouponType", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string getCouponType() {
            object[] results = this.Invoke("getCouponType", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void getCouponTypeAsync() {
            this.getCouponTypeAsync(null);
        }
        
        /// <remarks/>
        public void getCouponTypeAsync(object userState) {
            if ((this.getCouponTypeOperationCompleted == null)) {
                this.getCouponTypeOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetCouponTypeOperationCompleted);
            }
            this.InvokeAsync("getCouponType", new object[0], this.getCouponTypeOperationCompleted, userState);
        }
        
        private void OngetCouponTypeOperationCompleted(object arg) {
            if ((this.getCouponTypeCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getCouponTypeCompleted(this, new getCouponTypeCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ValidatePC", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string ValidatePC(string xmlStr) {
            object[] results = this.Invoke("ValidatePC", new object[] {
                        xmlStr});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void ValidatePCAsync(string xmlStr) {
            this.ValidatePCAsync(xmlStr, null);
        }
        
        /// <remarks/>
        public void ValidatePCAsync(string xmlStr, object userState) {
            if ((this.ValidatePCOperationCompleted == null)) {
                this.ValidatePCOperationCompleted = new System.Threading.SendOrPostCallback(this.OnValidatePCOperationCompleted);
            }
            this.InvokeAsync("ValidatePC", new object[] {
                        xmlStr}, this.ValidatePCOperationCompleted, userState);
        }
        
        private void OnValidatePCOperationCompleted(object arg) {
            if ((this.ValidatePCCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ValidatePCCompleted(this, new ValidatePCCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ConsumePC", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string ConsumePC(string xmlStr) {
            object[] results = this.Invoke("ConsumePC", new object[] {
                        xmlStr});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void ConsumePCAsync(string xmlStr) {
            this.ConsumePCAsync(xmlStr, null);
        }
        
        /// <remarks/>
        public void ConsumePCAsync(string xmlStr, object userState) {
            if ((this.ConsumePCOperationCompleted == null)) {
                this.ConsumePCOperationCompleted = new System.Threading.SendOrPostCallback(this.OnConsumePCOperationCompleted);
            }
            this.InvokeAsync("ConsumePC", new object[] {
                        xmlStr}, this.ConsumePCOperationCompleted, userState);
        }
        
        private void OnConsumePCOperationCompleted(object arg) {
            if ((this.ConsumePCCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ConsumePCCompleted(this, new ConsumePCCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/csmSuccess", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool csmSuccess(string xmlStr) {
            object[] results = this.Invoke("csmSuccess", new object[] {
                        xmlStr});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void csmSuccessAsync(string xmlStr) {
            this.csmSuccessAsync(xmlStr, null);
        }
        
        /// <remarks/>
        public void csmSuccessAsync(string xmlStr, object userState) {
            if ((this.csmSuccessOperationCompleted == null)) {
                this.csmSuccessOperationCompleted = new System.Threading.SendOrPostCallback(this.OncsmSuccessOperationCompleted);
            }
            this.InvokeAsync("csmSuccess", new object[] {
                        xmlStr}, this.csmSuccessOperationCompleted, userState);
        }
        
        private void OncsmSuccessOperationCompleted(object arg) {
            if ((this.csmSuccessCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.csmSuccessCompleted(this, new csmSuccessCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetZF_SMS_DATA", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet GetZF_SMS_DATA(string companyId) {
            object[] results = this.Invoke("GetZF_SMS_DATA", new object[] {
                        companyId});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void GetZF_SMS_DATAAsync(string companyId) {
            this.GetZF_SMS_DATAAsync(companyId, null);
        }
        
        /// <remarks/>
        public void GetZF_SMS_DATAAsync(string companyId, object userState) {
            if ((this.GetZF_SMS_DATAOperationCompleted == null)) {
                this.GetZF_SMS_DATAOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetZF_SMS_DATAOperationCompleted);
            }
            this.InvokeAsync("GetZF_SMS_DATA", new object[] {
                        companyId}, this.GetZF_SMS_DATAOperationCompleted, userState);
        }
        
        private void OnGetZF_SMS_DATAOperationCompleted(object arg) {
            if ((this.GetZF_SMS_DATACompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetZF_SMS_DATACompleted(this, new GetZF_SMS_DATACompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/SetSMS_DATA_STATE", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string SetSMS_DATA_STATE(string companyId, string upID) {
            object[] results = this.Invoke("SetSMS_DATA_STATE", new object[] {
                        companyId,
                        upID});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void SetSMS_DATA_STATEAsync(string companyId, string upID) {
            this.SetSMS_DATA_STATEAsync(companyId, upID, null);
        }
        
        /// <remarks/>
        public void SetSMS_DATA_STATEAsync(string companyId, string upID, object userState) {
            if ((this.SetSMS_DATA_STATEOperationCompleted == null)) {
                this.SetSMS_DATA_STATEOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSetSMS_DATA_STATEOperationCompleted);
            }
            this.InvokeAsync("SetSMS_DATA_STATE", new object[] {
                        companyId,
                        upID}, this.SetSMS_DATA_STATEOperationCompleted, userState);
        }
        
        private void OnSetSMS_DATA_STATEOperationCompleted(object arg) {
            if ((this.SetSMS_DATA_STATECompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SetSMS_DATA_STATECompleted(this, new SetSMS_DATA_STATECompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetChangePointPC", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GetChangePointPC(string xmlStr) {
            object[] results = this.Invoke("GetChangePointPC", new object[] {
                        xmlStr});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetChangePointPCAsync(string xmlStr) {
            this.GetChangePointPCAsync(xmlStr, null);
        }
        
        /// <remarks/>
        public void GetChangePointPCAsync(string xmlStr, object userState) {
            if ((this.GetChangePointPCOperationCompleted == null)) {
                this.GetChangePointPCOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetChangePointPCOperationCompleted);
            }
            this.InvokeAsync("GetChangePointPC", new object[] {
                        xmlStr}, this.GetChangePointPCOperationCompleted, userState);
        }
        
        private void OnGetChangePointPCOperationCompleted(object arg) {
            if ((this.GetChangePointPCCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetChangePointPCCompleted(this, new GetChangePointPCCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/DelChangePointLog", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string DelChangePointLog(string companyId, string upID) {
            object[] results = this.Invoke("DelChangePointLog", new object[] {
                        companyId,
                        upID});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void DelChangePointLogAsync(string companyId, string upID) {
            this.DelChangePointLogAsync(companyId, upID, null);
        }
        
        /// <remarks/>
        public void DelChangePointLogAsync(string companyId, string upID, object userState) {
            if ((this.DelChangePointLogOperationCompleted == null)) {
                this.DelChangePointLogOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDelChangePointLogOperationCompleted);
            }
            this.InvokeAsync("DelChangePointLog", new object[] {
                        companyId,
                        upID}, this.DelChangePointLogOperationCompleted, userState);
        }
        
        private void OnDelChangePointLogOperationCompleted(object arg) {
            if ((this.DelChangePointLogCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.DelChangePointLogCompleted(this, new DelChangePointLogCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/PosVipOpenPC", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string PosVipOpenPC(string companyId, string xmlStr) {
            object[] results = this.Invoke("PosVipOpenPC", new object[] {
                        companyId,
                        xmlStr});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void PosVipOpenPCAsync(string companyId, string xmlStr) {
            this.PosVipOpenPCAsync(companyId, xmlStr, null);
        }
        
        /// <remarks/>
        public void PosVipOpenPCAsync(string companyId, string xmlStr, object userState) {
            if ((this.PosVipOpenPCOperationCompleted == null)) {
                this.PosVipOpenPCOperationCompleted = new System.Threading.SendOrPostCallback(this.OnPosVipOpenPCOperationCompleted);
            }
            this.InvokeAsync("PosVipOpenPC", new object[] {
                        companyId,
                        xmlStr}, this.PosVipOpenPCOperationCompleted, userState);
        }
        
        private void OnPosVipOpenPCOperationCompleted(object arg) {
            if ((this.PosVipOpenPCCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.PosVipOpenPCCompleted(this, new PosVipOpenPCCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/SendSaleMsg", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string SendSaleMsg(string companyId, string xmlStr) {
            object[] results = this.Invoke("SendSaleMsg", new object[] {
                        companyId,
                        xmlStr});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void SendSaleMsgAsync(string companyId, string xmlStr) {
            this.SendSaleMsgAsync(companyId, xmlStr, null);
        }
        
        /// <remarks/>
        public void SendSaleMsgAsync(string companyId, string xmlStr, object userState) {
            if ((this.SendSaleMsgOperationCompleted == null)) {
                this.SendSaleMsgOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSendSaleMsgOperationCompleted);
            }
            this.InvokeAsync("SendSaleMsg", new object[] {
                        companyId,
                        xmlStr}, this.SendSaleMsgOperationCompleted, userState);
        }
        
        private void OnSendSaleMsgOperationCompleted(object arg) {
            if ((this.SendSaleMsgCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SendSaleMsgCompleted(this, new SendSaleMsgCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/SendLpcApplyResMsg", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string SendLpcApplyResMsg(string companyId, string xmlStr) {
            object[] results = this.Invoke("SendLpcApplyResMsg", new object[] {
                        companyId,
                        xmlStr});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void SendLpcApplyResMsgAsync(string companyId, string xmlStr) {
            this.SendLpcApplyResMsgAsync(companyId, xmlStr, null);
        }
        
        /// <remarks/>
        public void SendLpcApplyResMsgAsync(string companyId, string xmlStr, object userState) {
            if ((this.SendLpcApplyResMsgOperationCompleted == null)) {
                this.SendLpcApplyResMsgOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSendLpcApplyResMsgOperationCompleted);
            }
            this.InvokeAsync("SendLpcApplyResMsg", new object[] {
                        companyId,
                        xmlStr}, this.SendLpcApplyResMsgOperationCompleted, userState);
        }
        
        private void OnSendLpcApplyResMsgOperationCompleted(object arg) {
            if ((this.SendLpcApplyResMsgCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SendLpcApplyResMsgCompleted(this, new SendLpcApplyResMsgCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/hello", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string hello(string x) {
            object[] results = this.Invoke("hello", new object[] {
                        x});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void helloAsync(string x) {
            this.helloAsync(x, null);
        }
        
        /// <remarks/>
        public void helloAsync(string x, object userState) {
            if ((this.helloOperationCompleted == null)) {
                this.helloOperationCompleted = new System.Threading.SendOrPostCallback(this.OnhelloOperationCompleted);
            }
            this.InvokeAsync("hello", new object[] {
                        x}, this.helloOperationCompleted, userState);
        }
        
        private void OnhelloOperationCompleted(object arg) {
            if ((this.helloCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.helloCompleted(this, new helloCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void GetNewPCwithTidCompletedEventHandler(object sender, GetNewPCwithTidCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetNewPCwithTidCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetNewPCwithTidCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void GetAllPCwithTIDCompletedEventHandler(object sender, GetAllPCwithTIDCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetAllPCwithTIDCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetAllPCwithTIDCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void GetNewPCwithPOSCompletedEventHandler(object sender, GetNewPCwithPOSCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetNewPCwithPOSCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetNewPCwithPOSCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void getCouponTypeCompletedEventHandler(object sender, getCouponTypeCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getCouponTypeCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getCouponTypeCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void ValidatePCCompletedEventHandler(object sender, ValidatePCCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ValidatePCCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ValidatePCCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void ConsumePCCompletedEventHandler(object sender, ConsumePCCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ConsumePCCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ConsumePCCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void csmSuccessCompletedEventHandler(object sender, csmSuccessCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class csmSuccessCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal csmSuccessCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void GetZF_SMS_DATACompletedEventHandler(object sender, GetZF_SMS_DATACompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetZF_SMS_DATACompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetZF_SMS_DATACompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void SetSMS_DATA_STATECompletedEventHandler(object sender, SetSMS_DATA_STATECompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SetSMS_DATA_STATECompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SetSMS_DATA_STATECompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void GetChangePointPCCompletedEventHandler(object sender, GetChangePointPCCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetChangePointPCCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetChangePointPCCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void DelChangePointLogCompletedEventHandler(object sender, DelChangePointLogCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class DelChangePointLogCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal DelChangePointLogCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void PosVipOpenPCCompletedEventHandler(object sender, PosVipOpenPCCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class PosVipOpenPCCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal PosVipOpenPCCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void SendSaleMsgCompletedEventHandler(object sender, SendSaleMsgCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SendSaleMsgCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SendSaleMsgCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void SendLpcApplyResMsgCompletedEventHandler(object sender, SendLpcApplyResMsgCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SendLpcApplyResMsgCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SendLpcApplyResMsgCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void helloCompletedEventHandler(object sender, helloCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class helloCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal helloCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591